### ISSUE TITLE
Wrong information about megabytes vs mebibytes

### ISSUE THREAD

**Issue by jvschiavo** [koalaman/linuxatemyram.com#12]
There is some wrong information in the section: "How do I see how much free ram I really have?"

It says:
"This is your answer in megabytes."
When it actually should say:
"This is your answer in mebibytes."

Source: `man free`, Megabyte and Mebibyte wikipedia pages.

**Comment by koalaman** [comment]
Fixed. Technically correct is the best kind of correct.
