### ISSUE TITLE
https!

### ISSUE THREAD

**Issue by Goury** [koalaman/linuxatemyram.com#2]
Come on, its 2017 already, https the website!

https://www.ssllabs.com/ssltest/analyze.html?d=linuxatemyram.com&hideResults=on

**Comment by v0idst4r** [comment]
You're POSTing passwords to linuxatemyram.com?

**Comment by dannycolin** [comment]
> @v0idst4r : You're POSTing passwords to linuxatemyram.com?

 https isn't only about password...

**Comment by v0idst4r** [comment]
@dannycolin Then what do you propose the purpose of making linuxatemyram https would be?

**Comment by Goury** [comment]
Can we please also ban all trolls and generally illeterate and dumb people?

Sincerely, https://lmgtfy.com/?q=why+https+is+important

**Comment by koalaman** [comment]
HTTPS is now an option!

That tool complains when not adding www, but Chrome does not and redirects.

**Comment by v0idst4r** [comment]
@Goury Who gives a damn if you visit linuxatemyram.com? There's absolutely no reason to add encryption to this website because there's no sensitive data being transferred at all

**Comment by Goury** [comment]
@koalaman Tool complains that you deployed it wrongly. MITM won't care about your www, it will just replace your redirect with whatever he wants.

@v0idst4r I will not answer to trolling nor to dilettantism.

**Comment by v0idst4r** [comment]
Privacy cooks at their finest

**Comment by koalaman** [comment]
Ah, here we go: "Redirecting navigation linuxatemyram.com -> www.linuxatemyram.com because the server presented a certificate valid for www.linuxatemyram.com but not for linuxatemyram.com."

That's some MSIE6 level compatibility bs, but at least it's not unencrypted.

**Comment by Goury** [comment]
@koalaman redirects should be valid https as well as any other response from server.
You are the one who just ignoring standarts, like MSIE.
Including this www atavism.

So please do fix it for real already.
The fact you don't recognize or don't understand the problem only means you are not skilled enough to prevent such problems.

Problem is present and it is major security breach for every user out there.

**Comment by koalaman** [comment]
I appreciate your enthusiasm for security, even when it fails to differentiate between a browser feature and an unencrypted/misauthenticated server redirect.

https://linuxatemyram.com is now correctly authenticated.

**Comment by dannycolin** [comment]
+1 it works perfectly now. :)

**Comment by Goury** [comment]
When it comes to security, there is only two ways — secure way and insecure way. Single flaw in security ruins every effort you are putting into it.

AS BF once said, those who a willing to trade security for laziness deserve neither and will eventually loose both.

I am sincerely glad that Linux ate my ram securely today!
