### ISSUE TITLE
Add disk and memory specifications

### ISSUE THREAD

**Issue by mlalkaka** [koalaman/linuxatemyram.com#20]
Thanks for this website! It was really helpful in learning how the disk cache works and how to interpret memory metrics.

Could you please add the basic specifications of the hard drive and memory you used on the page with real measurements? I'm curious if those measurements were made on a spinning hard disk or an SSD, for example. 

Some good specifications to share might be:
 * SSD or HDD?
 * SATA or NVMe connection?
 * RAM type (DDR4, etc)

**Comment by koalaman** [comment]
I've added a warning that this was on spinning rust anno 2009. At some point I should re-run them on modern hardware.
