### ISSUE TITLE
different memory info format

### ISSUE THREAD

**Issue by jingpengw** [koalaman/linuxatemyram.com#3]
this is a funny website. my `free` in ubuntu14.04 shows an extra line of `-/+ buffers/cache:`.
this shows the real `free` memory I think.

**Comment by koalaman** [comment]
Thanks! You're right, this is the old format that was used up until ~2016. 

LinuxAteMyRam.com showed both formats up until earlier this year, when it was finally retired in favor of the new format. I re-added a note about this.
